src/Web/SGL.WebUI/Controllers/ContasPagarController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SGL.Integrations.Interfaces;
using SGL.Integrations.ViewModels;

namespace SGL.WebUI.Controllers
{
    public class ContasPagarController : BaseController
    {
        private readonly IContasPagarService _contasPagarService;
        private readonly IFornecedorService _fornecedorService;
        public ContasPagarController(IContasPagarService contasPagarService, IFornecedorService fornecedorService)
        {
            _contasPagarService = contasPagarService;
            _fornecedorService = fornecedorService;
        }

        // GET: ContasPagarController
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var token = await GetToken();
            var ContasPagar = await _contasPagarService.ObterTodosContasPagars(token);
            return View(ContasPagar);
        }

        // GET: ContasPagarController/Create
        [Authorize]
        public async Task<ActionResult> Create()
        {
            var token = await GetToken();
            var fornecedores = await _fornecedorService.ObterTodosFornecedores(token);
            var contasPagar = new ContasPagarViewModel
            {
                FornecedorViewModels = fornecedores.ToList(),
                StatusVieModels = _contasPagarService.TodosStatus()
            };

            return View(contasPagar);
        }

        // POST: ContasPagarController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(ContasPagarViewModel contasPagarViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                contasPagarViewModel.Valor /= 100.0M;

                var token = await GetToken();
                var result = await _contasPagarService.Adicionar(contasPagarViewModel, token);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ContasPagarController/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(Guid id)
        {
            var token = await GetToken();
            var contasPagar = await _contasPagarService.ObterContasPagarPorId(id, token);
            var fornecedor = await _fornecedorService.ObterTodosFornecedores(token);
            contasPagar.FornecedorViewModels = fornecedor.ToList();
            contasPagar.StatusVieModels = _contasPagarService.TodosStatus();
            return View(contasPagar);
        }

        // POST: ContasPagarController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(ContasPagarViewModel contasPagarViewModel)
        {
            if (!ModelState.IsValid)
                return View();

            contasPagarViewModel.Valor /= 100.0M;

            var token = await GetToken();
            var result = await _contasPagarService.Atualizar(contasPagarViewModel, token);

            return RedirectToAction(nameof(Index));
        }

        // GET: ContasPagarController/Details/5
        [Authorize]
        public async Task<IActionResult> Details(Guid id)
        {
            var token = await GetToken();
            var contasPagar = await _contasPagarService.ObterContasPagarPorId(id, token);
            return View(contasPagar);
        }
    }
}

src/Web/SGL.WebUI/Views/ContasPagar/Create.cshtml
@model ContasPagarViewModel

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Horizontal Form -->
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Cadastro de Contas a Pagar</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form asp-controller="ContasPagar" asp-action="Create" class="form-horizontal" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="card-body">
                        <div class="form-group row d-none">
                            <label asp-for="Id" class="col-sm-2 col-form-label">Id</label>
                            <div class="col-sm-10">
                                <input asp-for="Id" class="form-control" placeholder="Id">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label asp-for="FornecedorId" class="control-label"></label>
                                    <select asp-for="FornecedorId" class="form-control" asp-items="@(new SelectList(Model.FornecedorViewModels, "Id", "NomeFantasia"))">
                                        <option></option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="Descricao" class="control-label"></label>
                                    <input asp-for="Descricao" class="form-control" placeholder="Descrição">
                                    <span asp-validation-for="Descricao" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="DataVencimento" class="control-label"></label>
                                    <input asp-for="DataVencimento" class="form-control" placeholder="Data de Vencimento">
                                    <span asp-validation-for="DataVencimento" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="Valor" class="control-label"></label>
                                    <input asp-for="Valor" class="form-control" placeholder="Valor">
                                    <span asp-validation-for="Valor" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-info">Salvar</button>
                        <a asp-action="Index" class="btn btn-default float-right">Voltar</a>
                    </div>
                    <!-- /.card-footer -->
                </form>
            </div>
            <!-- /.card -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            $('#DataVencimento').setMask({ mask: "99/99/9999" });
            $('#Valor').setMask({ mask: '99.999.999.999.999', type: 'reverse' });
        });
    </script>
}

src/Web/SGL.WebUI/Views/ContasPagar/Details.cshtml
@model ContasPagarViewModel
<!-- Content Wrapper. Contains page content -->
<style>
    label:not(.form-check-label):not(.custom-file-label) {
        text-align: right;
    }
</style>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Horizontal Form -->
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Detalhes de Contas a Pagar</h3>
                </div>
                <div class="card-body">
                    <div class="form-group row">
                        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <span class="form-control">@Html.DisplayFor(model => model.Id)</span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="FornecedorId" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                              <span class="form-control">@Html.DisplayFor(model => model.ResponseFornecedorOut.RazaoSocial)</span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label asp-for="Descricao" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <span class="form-control">@Html.DisplayFor(model => model.Descricao)</span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label asp-for="DataVencimento" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <span class="form-control">@Html.DisplayFor(model => model.DataVencimento)</span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label asp-for="Valor" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <span class="form-control">@Html.DisplayFor(model => model.Valor)</span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label asp-for="Situacao" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <span class="form-control">@Html.DisplayFor(model => model.Situacao)</span>
                        </div>
                    </div>
                </div>

                <!-- /.card-body -->
                <div class="card-footer">
                    @if (User.IsInRole("Administrador"))
                    {
                        <a asp-controller="ContasPagar" asp-action="Edit" asp-route-id="@Model.Id">
                            <i class="bi bi-pencil-square btn btn-primary" aria-hidden="true" title="Editar"></i>
                        </a>
                    }
                    <a asp-action="Index" class="btn btn-default float-right">Voltar</a>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
</div>

src/Web/SGL.WebUI/Views/ContasPagar/Edit.cshtml
@model ContasPagarViewModel

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Horizontal Form -->
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Atualização de Contas a Pagar</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form asp-controller="ContasPagar" asp-action="Edit" class="form-horizontal" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="card-body">
                        <div class="row d-none">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label asp-for="Id" class="control-label"></label>
                                    <input asp-for="Id" class="form-control" placeholder="Id" disabled>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label asp-for="FornecedorId" class="control-label"></label>
                                    <select asp-for="FornecedorId" class="form-control" asp-items="@(new SelectList(Model.FornecedorViewModels, "Id", "NomeFantasia"))">
                                        <option></option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label asp-for="Descricao" class="control-label"></label>
                                    <input asp-for="Descricao" class="form-control" placeholder="Descrição">
                                    <span asp-validation-for="Descricao" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label asp-for="DataVencimento" class="control-label"></label>
                                    <input asp-for="DataVencimento" class="form-control" placeholder="Data de Vencimento">
                                    <span asp-validation-for="DataVencimento" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label asp-for="Valor" class="control-label"></label>
                                    <input asp-for="Valor" class="form-control" placeholder="Valor">
                                    <span asp-validation-for="Valor" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label asp-for="Situacao" class="control-label"></label>
                                    <select asp-for="Situacao" class="form-control" asp-items="@(new SelectList(Model.StatusVieModels, "Situacao", "Descricao"))">
                                        <option></option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-info">Alterar</button>
                        <a asp-action="Index" class="btn btn-default float-right">Voltar</a>
                    </div>
                    <!-- /.card-footer -->
                </form>
            </div>
            <!-- /.card -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            //$('#DataVencimento').setMask({ mask: "99/99/9999 99:99" });
            //$('#DataVencimento').trigger();
            $('#Valor').setMask({ mask: '99.999.999.999.999', type: 'reverse' });
        });
    </script>
}

src/Web/SGL.WebUI/Views/ContasPagar/Index.cshtml
@model IEnumerable<ContasPagarViewModel>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Lista de Contas a Pagar</h3>
                    <div style="text-align:right; margin-top: 10px">
                        @if (User.IsInRole("Administrador"))
                        {
                            <a asp-controller="ContasPagar" asp-action="Create" class="btn btn-success"> Novo Cadastro</a>
                        }
                    </div>
                </div>
            </div>
            <div class="card">

                <!-- /.card-header -->
                <div class="card-body p-0">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th class="d-none">
                                    @Html.DisplayNameFor(model => model.Id)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.FornecedorId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Descricao)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DataVencimento)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Valor)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ObterSituacao)
                                </th>
                                <th>Ações</th>
                            </tr>
                        </thead>

                        <tbody>
                            @if (Model != null)
                            {
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="d-none">
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ResponseFornecedorOut.NomeFantasia)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Descricao)
                                        </td>
                                        <td style="text-align:center;">
                                            @Html.DisplayFor(modelItem => item.DataVencimento)
                                        </td>
                                        <td style="text-align:right;">
                                            @Html.DisplayFor(modelItem => item.Valor)
                                        </td>
                                        <td style="text-align:center;">
                                            @Html.DisplayFor(modelItem => item.ObterSituacao)
                                        </td>
                                        <td>
                                            @if (User.IsInRole("Administrador"))
                                            {
                                                <a asp-controller="ContasPagar" asp-action="Edit" asp-route-id="@item.Id">
                                                    <i class="bi bi-pencil-square btn btn-primary" aria-hidden="true" title="Editar"></i>
                                                </a>

                                                <a asp-controller="ContasPagar" asp-action="Baixar" asp-route-id="@item.Id">
                                                    <i class="bi bi-cash-stack btn btn-success" aria-hidden="true" title="Baixar Conta"></i>
                                                </a>
                                            }
                                            @if (User.IsInRole("Administrador") || User.IsInRole("Operador"))
                                            {
                                                <a asp-controller="ContasPagar" asp-action="Details" asp-route-id="@item.Id">
                                                    <i class="bi bi-ticket-detailed btn btn-info" aria-hidden="true" title="Details"></i>
                                                </a>
                                            }
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->

        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>