src/Web/SGL.WebUI/Controllers/FornecedorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SGL.Integrations.Interfaces;
using SGL.Integrations.ViewModels;

namespace SGL.WebUI.Controllers
{
    public class FornecedorController : BaseController
    {
        private readonly IFornecedorService _fornecedorService;

        public FornecedorController(IFornecedorService fornecedorService)
        {
            _fornecedorService = fornecedorService;
        }

        // GET: FornecedorController
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var token = await GetToken();
            var fornecedor = await _fornecedorService.ObterTodosFornecedores(token);
            return View(fornecedor);
        }

        // GET: FornecedorController/Create
        [Authorize]
        public ActionResult Create()
        {
            var fornecedor = new FornecedorViewModel
            {
                Estados = _fornecedorService.TodosEstados()
            };
            return View(fornecedor);
        }

        // POST: FornecedorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(FornecedorViewModel fornecedorViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                var token = await GetToken();
                var result = await _fornecedorService.Adicionar(fornecedorViewModel, token);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FornecedorController/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(Guid id)
        {
            var token = await GetToken();
            var fornecedor = await _fornecedorService.ObterFornecedorPorId(id, token);
            fornecedor.Estados = _fornecedorService.TodosEstados();
            return View(fornecedor);
        }

        // POST: FornecedorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(FornecedorViewModel fornecedorViewModel)
        {
            if (!ModelState.IsValid)
                return View();

            var token = await GetToken();
            var result = await _fornecedorService.Atualizar(fornecedorViewModel, token);

            return RedirectToAction(nameof(Index));
        }

        // GET: FornecedorController/Details/5
        [Authorize]
        public async Task<IActionResult> Details(Guid id)
        {
            var token = await GetToken();
            var fornecedor = await _fornecedorService.ObterFornecedorPorId(id, token);
            return View(fornecedor);
        }
    }
}

src/Web/SGL.WebUI/Views/Fornecedor/Create.cshtml
@model FornecedorViewModel
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Horizontal Form -->
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Cadastro de Formecedor</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->

                <form asp-controller="Fornecedor" asp-action="Create" class="form-horizontal" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="card-body">
                        <div class="form-group d-none">
                            <label asp-for="Id" class="control-label"></label>
                            <input asp-for="Id" class="form-control" />
                            <span asp-validation-for="Id" class="text-danger"></span>
                        </div>

                        <!--RazaoSocial, NomeFantasia e CNPJ-->
                        <div class="row">
                            <div class="col-sm-4">
                                <!-- text input -->
                                <div class="form-group">
                                    <label asp-for="RazaoSocial" class="control-label"></label>
                                    <input asp-for="RazaoSocial" class="form-control" />
                                    <span asp-validation-for="RazaoSocial" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="NomeFantasia" class="control-label"></label>
                                    <input asp-for="NomeFantasia" class="form-control" />
                                    <span asp-validation-for="NomeFantasia" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <!-- text input -->
                                <div class="form-group">
                                    <label asp-for="CNPJ" class="control-label"></label>
                                    <input asp-for="CNPJ" class="form-control" />
                                    <span asp-validation-for="CNPJ" class="text-danger"></span>
                                </div>
                            </div>
                        </div>

                        <!--InscricaoEstadual, Celular e E-mail-->
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="InscricaoEstadual" class="control-label"></label>
                                    <input asp-for="InscricaoEstadual" class="form-control" />
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <!-- text input -->
                                <div class="form-group">
                                    <label asp-for="Celular" class="control-label"></label>
                                    <input asp-for="Celular" class="form-control" />
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="EnderecoEmail" class="control-label"></label>
                                    <input asp-for="EnderecoEmail" class="form-control" />
                                </div>
                            </div>
                        </div>

                        <!--CEP, Logradouro, Bairro, Cidade e UF-->
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="CEP" class="control-label"></label>
                                    <input asp-for="CEP" class="form-control" />
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <!-- text input -->
                                <div class="form-group">
                                    <label asp-for="Logradouro" class="control-label"></label>
                                    <input asp-for="Logradouro" class="form-control" />
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="Bairro" class="control-label"></label>
                                    <input asp-for="Bairro" class="form-control" />
                                </div>
                            </div>
                        </div>


                        <!--Cidade e UF-->
                        <div class="row">
                            <div class="col-sm-6">
                                <!-- text input -->
                                <div class="form-group">
                                    <label asp-for="Cidade" class="control-label"></label>
                                    <input asp-for="Cidade" class="form-control" />
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label asp-for="Estado" class="control-label"></label>
                                    <select asp-for="Estado" class="form-control" asp-items="@(new SelectList(Model.Estados, "UF", "Descricao"))">
                                        <option></option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-info">Salvar</button>
                        <a asp-action="Index" class="btn btn-default float-right">Voltar</a>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            $('#CNPJ').setMask({ mask: '99.999.999/9999-99'});
            $('#CEP').setMask({ mask: '99999-999'});
            $('#Celular').setMask({ mask: '(99) 99999-9999'});
            $('#InscricaoEstadual').setMask({ mask: '99-999999-9' });
        });
    </script>
}

src/Web/SGL.WebUI/Views/Fornecedor/Details.cshtml
@model FornecedorViewModel

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Horizontal Form -->
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Detalhes de Fornecedor</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label asp-for="Id" class="control-label">Id</label>
                                <span class="form-control">@Html.DisplayFor(model => model.Id)</span>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <label asp-for="RazaoSocial" class="control-label"></label>
                                <span class="form-control">@Html.DisplayFor(model => model.RazaoSocial)</span>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <label asp-for="NomeFantasia" class="control-label"></label>
                                <span class="form-control">@Html.DisplayFor(model => model.NomeFantasia)</span>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <label asp-for="CNPJ" class="control-label"></label>
                                <span class="form-control">@Html.DisplayFor(model => model.CNPJ)</span>
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label asp-for="InscricaoEstadual" class="control-label"></label>
                                <span class="form-control">
                                    @Html.DisplayFor(model => model.InscricaoEstadual)
                                </span>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <label asp-for="Celular" class="control-label"></label>
                                <span class="form-control">
                                    @Html.DisplayFor(model => model.Celular)
                                </span>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <label asp-for="EnderecoEmail" class="control-label"></label>
                                <span class="form-control">
                                    @Html.DisplayFor(model => model.EnderecoEmail)
                                </span>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <label asp-for="Logradouro" class="control-label"></label>
                                <span class="form-control">
                                    @Html.DisplayFor(model => model.Logradouro)
                                </span>
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-sm-3">
                            <label asp-for="Bairro" class="control-label"></label>
                            <div class="form-group">
                                <span class="form-control">
                                    @Html.DisplayFor(model => model.Bairro)
                                </span>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <label asp-for="Cidade" class="control-label"></label>
                            <div class="form-group">
                                <span class="form-control">
                                    @Html.DisplayFor(model => model.Cidade)
                                </span>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <label asp-for="CEP" class="control-label"></label>
                            <div class="form-group">
                                <span class="form-control">
                                    @Html.DisplayFor(model => model.CEP)
                                </span>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <label asp-for="Estado" class="control-label"></label>
                            <div class="form-group">
                                <span class="form-control">
                                    @Html.DisplayFor(model => model.Estado)
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    @if (User.IsInRole("Administrador"))
                    {
                        <a asp-controller="Fornecedor" asp-action="Edit" asp-route-id="@Model.Id">
                            <i class="bi bi-pencil-square btn btn-primary" aria-hidden="true" title="Editar"></i>
                        </a>
                    }
                    <a asp-action="Index" class="btn btn-default float-right">Voltar</a>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
</div>

src/Web/SGL.WebUI/Views/Fornecedor/Edit.cshtml
@model FornecedorViewModel
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Horizontal Form -->
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Alteração de Formecedor</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->

                <form asp-controller="Fornecedor" asp-action="Edit" class="form-horizontal" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="card-body">
                        <div class="form-group d-none">
                            <label asp-for="Id" class="control-label"></label>
                            <input asp-for="Id" class="form-control" />
                            <span asp-validation-for="Id" class="text-danger"></span>
                        </div>

                        <!--RazaoSocial, NomeFantasia e CNPJ-->
                        <div class="row">
                            <div class="col-sm-4">
                                <!-- text input -->
                                <div class="form-group">
                                    <label asp-for="RazaoSocial" class="control-label"></label>
                                    <input asp-for="RazaoSocial" class="form-control" />
                                    <span asp-validation-for="RazaoSocial" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="NomeFantasia" class="control-label"></label>
                                    <input asp-for="NomeFantasia" class="form-control" />
                                    <span asp-validation-for="NomeFantasia" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <!-- text input -->
                                <div class="form-group">
                                    <label asp-for="CNPJ" class="control-label"></label>
                                    <input asp-for="CNPJ" class="form-control" />
                                    <span asp-validation-for="CNPJ" class="text-danger"></span>
                                </div>
                            </div>
                        </div>

                        <!--InscricaoEstadual, Celular e E-mail-->
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="InscricaoEstadual" class="control-label"></label>
                                    <input asp-for="InscricaoEstadual" class="form-control" />
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <!-- text input -->
                                <div class="form-group">
                                    <label asp-for="Celular" class="control-label"></label>
                                    <input asp-for="Celular" class="form-control" />
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="EnderecoEmail" class="control-label"></label>
                                    <input asp-for="EnderecoEmail" class="form-control" />
                                </div>
                            </div>
                        </div>

                        <!--CEP, Logradouro, Bairro, Cidade e UF-->
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="CEP" class="control-label"></label>
                                    <input asp-for="CEP" class="form-control" />
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <!-- text input -->
                                <div class="form-group">
                                    <label asp-for="Logradouro" class="control-label"></label>
                                    <input asp-for="Logradouro" class="form-control" />
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label asp-for="Bairro" class="control-label"></label>
                                    <input asp-for="Bairro" class="form-control" />
                                </div>
                            </div>
                        </div>

                        <!--Cidade e UF-->
                        <div class="row">
                            <div class="col-sm-6">
                                <!-- text input -->
                                <div class="form-group">
                                    <label asp-for="Cidade" class="control-label"></label>
                                    <input asp-for="Cidade" class="form-control" />
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label asp-for="Estado" class="control-label"></label>
                                    <select asp-for="Estado" class="form-control" asp-items="@(new SelectList(Model.Estados, "UF", "Descricao"))">
                                        <option></option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-info">Atualizaar</button>
                        <a asp-action="Index" class="btn btn-default float-right">Voltar</a>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            $('#CNPJ').setMask({ mask: '99.999.999/9999-99'});
            $('#CEP').setMask({ mask: '99999-999'});
            $('#Celular').setMask({ mask: '(99) 99999-9999'});
            $('#InscricaoEstadual').setMask({ mask: '99-999999-9' });
        });
    </script>
}

src/Web/SGL.WebUI/Views/Fornecedor/Index.cshtml
@model IEnumerable<FornecedorViewModel>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Lista de Fornecedores</h3>
                    <div style="text-align:right; margin-top: 10px">
                        @if (User.IsInRole("Administrador"))
                        {
                            <a asp-controller="Fornecedor" asp-action="Create" class="btn btn-success"> Novo Cadastro</a>
                        }
                    </div>
                </div>
            </div>
            <div class="card">

                <!-- /.card-header -->
                <div class="card-body p-0">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th class="d-none">
                                    @Html.DisplayNameFor(model => model.Id)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.NomeFantasia)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CNPJ)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Celular)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.EnderecoEmail)
                                </th>
                                <th>Ações</th>
                            </tr>
                        </thead>

                        <tbody>
                            @if (Model != null)
                            {
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="d-none">
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.NomeFantasia)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CNPJ)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Celular)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.EnderecoEmail)
                                        </td>
                                        <td>
                                            @if (User.IsInRole("Administrador"))
                                            {
                                                <a asp-controller="Fornecedor" asp-action="Edit" asp-route-id="@item.Id">
                                                    <i class="bi bi-pencil-square btn btn-primary" aria-hidden="true" title="Editar"></i>
                                                </a>
                                            }

                                            @if (User.IsInRole("Administrador") || User.IsInRole("Operador"))
                                            {
                                                <a asp-controller="Fornecedor" asp-action="Details" asp-route-id="@item.Id">
                                                    <i class="bi bi-ticket-detailed btn btn-info" aria-hidden="true" title="Details"></i>
                                                </a>
                                            }
                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->

        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>